name: lment # Give your new environment a meaningful name
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Conda Packages (Base environment setup) ---
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=24.5.0=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312h06a4308_0
  - conda-package-streaming=0.10.0=py312h06a4308_0
  - cryptography=42.0.5=py312hdda0065_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_3
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py312h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - menuinst=2.1.1=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=23.2=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.0=py312h06a4308_0 # Keep pip as a direct Conda dependency
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.2=py312h06a4308_0
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - setuptools=69.5.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.4=py312he106c6f_0
  - truststore=0.8.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py312h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  
  # --- Pip Packages (from requirements.txt that are not Conda-installed) ---
  - pip:
    - absl-py==2.2.0
    - accelerate==1.5.2
    - adjustText==1.3.0
    - ai2-olmo==0.6.0
    - ai2-olmo-core==0.1.0
    - ai2-olmo-eval==0.5.0
    # Keep local file paths from original requirements.txt (as they must be installed by pip)
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - aiosignal==1.2.0 
    - alpaca_eval==0.6.6
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.11.0
    - anyio==4.8.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.17.0
    - backports.tarfile==1.2.0
    - beaker-gantry==1.13.0
    - beaker-py==1.34.1
    - beautifulsoup4==4.13.3
    - bitsandbytes==0.45.3
    - black==23.12.1
    - bleach==6.2.0
    - blis==1.3.3
    # Removed 'boltons' (Conda)
    - boto3==1.36.3
    - botocore==1.36.3
    - Bottleneck==1.4.2
    - Brotli==1.0.9 
    - build==1.2.2.post1
    - cachetools==5.5.1 
    - catalogue==2.0.10
    - certifi==2025.1.31
    # Removed 'cffi' (Conda)
    - chardet==5.2.0
    # Removed 'charset-normalizer' (Conda)
    - click==8.1.8
    - click-help-colors==0.9.4
    - cloudpathlib==0.23.0
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - comm==0.2.2
    - confection==0.1.5
    - contourpy==1.3.1
    # Removed 'cryptography' (Conda)
    - cycler==0.12.1
    - cymem==2.0.12
    - dask==2025.5.0
    - DataProperty==1.1.0
    - datasets==3.3.2
    - debugpy==1.8.12
    - decorator==5.2.1
    - defusedxml==0.7.1
    - Deprecated==1.2.13 
    - dill==0.3.8 
    # Removed 'distro' (Conda)
    - docker==7.1.0
    - docker-pycreds==0.4.0
    - docutils==0.21.2
    - einops==0.8.1
    - elastic-transport==8.17.1
    - elasticsearch==8.18.1
    - evaluate==0.4.3
    - executing==2.2.0
    - face==24.0.0
    - fastjsonschema==2.21.1
    - filelock==3.13.1
    - fire==0.7.0
    - fonttools==4.56.0
    - fqdn==1.5.1
    - frozenlist==1.5.0
    - fsspec==2023.5.0
    - ftfy==6.3.1
    - gitdb==4.0.12
    - GitPython==3.1.44
    - glom==24.11.0
    - gmpy2==2.2.1 
    - google-api-core==2.19.1 
    - google-api-python-client==2.165.0
    - google-auth==2.38.0 
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.2.1
    - google-cloud-core==2.3.2 
    - google-cloud-storage==2.18.0 
    - google-crc32c==1.6.0 
    - google-genai==1.20.0
    - google-resumable-media==2.7.1 
    - gradio_client==1.8.0
    - grpcio==1.62.2 
    - h11==0.14.0
    - hf-xet==1.1.10
    - hf_transfer==0.1.9
    - httpcore==1.0.7
    - httplib2==0.22.0
    - httpx==0.28.1
    - huggingface-hub==0.35.3
    - id==1.5.0
    # Removed 'idna' (Conda)
    - immutabledict==4.2.1
    - importlib-metadata==7.0.1  
    - importlib_resources==6.4.0
    - iniconfig==2.0.0
    - ipykernel==6.29.5
    - ipython==8.32.0
    - ipywidgets==8.1.7
    - isoduration==20.11.0
    - isort==5.12.0
    - itables==2.4.3
    - jaraco.classes==3.4.0
    - jaraco.context==6.0.1
    - jaraco.functools==4.1.0
    - jedi==0.19.2
    - jeepney==0.8.0
    - Jinja2==3.1.5 
    - jiter==0.9.0
    - jmespath==1.0.1 
    - joblib==1.4.2
    - json5==0.10.0
    - jsonlines==4.0.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - jupyter_server==2.15.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.3.5
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.3
    - jupyterlab_widgets==3.0.15
    - keyring==25.6.0
    - kiwisolver==1.4.8
    - langdetect==1.0.9
    - lightning-utilities==0.12.0
    - litellm==1.63.14
    - lm_eval==0.4.3
    - lmdb==1.6.2
    - locket==1.0.0
    - lxml==5.3.1
    - markdown-it-py==2.2.0 
    - MarkupSafe==3.0.2  
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mbstrdecoder==1.1.4
    - mdurl==0.1.0  
    - mistune==3.1.2
    - more-itertools==10.6.0
    - mpmath==1.3.0  
    - msgspec==0.19.0
    - multidict==6.1.0 
    - multiprocess==0.70.15 
    - murmurhash==1.0.15
    - mypy==1.3.0
    - mypy-extensions==1.0.0
    - narwhals==1.45.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - necessary==0.4.3
    - nest-asyncio==1.6.0
    - networkx==3.4.2 
    - nh3==0.2.21
    - nltk==3.9.1
    - notebook_shim==0.2.4
    - numexpr==2.10.1  
    - numpy==1.26.4 
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - omegaconf==2.4.0.dev3
    - openai==1.68.2
    - opentelemetry-api==1.26.0 
    - orjson==3.10.18
    - overrides==7.7.0
    # Removed 'packaging' (Conda)
    - pandas==2.2.3 
    - pandocfilters==1.5.1
    - parso==0.8.4
    - partd==1.4.2
    - pathspec==0.12.1
    - pathvalidate==3.2.3
    - patsy==1.0.1
    - peft==0.15.0
    - petname==2.6
    - pexpect==4.9.0
    - pillow==11.1.0
    # Removed 'platformdirs' (Conda)
    - plotly==6.2.0
    # Removed 'pluggy' (Conda)
    - polars==1.29.0
    - portalocker==3.1.1
    - preshed==3.0.12
    - prometheus_client==0.21.1
    - prompt_toolkit==3.0.50
    - propcache==0.2.0 
    - proto-plus==1.24.0 
    - protobuf==4.25.3
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pyarrow==19.0.0 
    - pyasn1==0.4.8  
    - pyasn1-modules==0.2.8
    - pybind11==2.13.6
    # Removed 'pycparser' (Conda)
    - pydantic==2.10.3 
    - pydantic_core==2.27.1
    - Pygments==2.15.1 
    - pygsheets==2.0.6
    - pyOpenSSL==24.2.1 
    - pyparsing==3.2.1
    - pyproject_hooks==1.2.0
    - pyrate-limiter==3.7.1
    # Removed 'PySocks' (Conda)
    - pytablewriter==1.2.1
    - pytest==8.3.4
    - pytest-sphinx==0.6.3
    - python-dateutil==2.9.0.post0 
    - python-dotenv==1.0.1
    - python-json-logger==3.2.1
    - pytrec_eval==0.5
    - pytz==2024.1 
    - PyYAML==6.0.2 
    - pyzmq==26.2.1
    - ratelimit==2.2.1
    - readme_renderer==44.0
    - referencing==0.36.2
    - regex==2024.11.6 
    # Removed 'requests' (Conda)
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - requirements-parser==0.11.0
    - rfc3339-validator==0.1.4
    - rfc3986==2.0.0
    - rfc3986-validator==0.1.1
    - rich==13.9.4 
    - rouge_score==0.1.2
    - rpds-py==0.23.1
    - rsa==4.7.2 
    - ruff==0.9.7
    - s3transfer==0.11.2  
    - sacrebleu==2.5.1
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - SecretStorage==3.3.3
    - Send2Trash==1.8.3
    - sentencepiece==0.2.1
    - sentry-sdk==2.22.0
    - setproctitle==1.3.5
    - six==1.16.0  
    - smart-open==7.1.0
    - smashed==0.21.5
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.6
    - spacy==3.8.11
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sqlitedict==2.1.0
    - srsly==2.5.2
    - stack-data==0.6.3
    - statsmodels==0.14.5
    - sympy==1.13.1
    - tabledata==1.3.4
    - tabulate==0.9.0
    - tcolorpy==0.1.7
    - tenacity==9.0.0
    - termcolor==2.5.0
    - terminado==0.18.1
    - thinc==8.3.10
    - threadpoolctl==3.5.0
    - tiktoken==0.9.0
    - tinycss2==1.4.0
    - tokenizers==0.22.1
    - toolz==1.0.0
    - torch==2.6.0
    - torchmetrics==1.6.1
    - tornado==6.4.2
    - tqdm==4.67.1 
    - tqdm-multiprocess==0.0.11
    - traitlets==5.14.3
    - transformers==4.56.2
    - tree-sitter==0.24.0
    - tree-sitter-python==0.23.6
    - triton==3.2.0
    - trouting==0.3.3
    - twine==6.1.0
    - typepy==1.3.4
    - typer-slim==0.21.0
    - types-python-dateutil==2.9.0.20241206
    - types-setuptools==75.8.0.20250225
    - typing_extensions==4.12.2 
    # Removed 'tzdata' (Conda)
    - ujson==5.10.0
    - Unidecode==1.4.0
    - uri-template==1.3.0
    - uritemplate==4.1.1
    # Removed 'urllib3' (Conda)
    - wandb==0.19.7
    - wasabi==1.1.3
    - wcwidth==0.2.13
    - weasel==0.4.3
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - websockets==15.0.1
    - widgetsnbextension==4.0.14
    - word2number==1.1
    - wrapt==1.17.0 
    - xxhash==3.5.0 
    - yarl==1.18.0 
    - zipp==3.21.0 
    # Removed 'zstandard' (Conda)
